yarnPath: .yarn/releases/yarn-3.1.1.cjs
cacheFolder: "./.yarn/cache"
defaultLanguageName: "node"
defaultProtocol: "npm:"
enableColors: true
enableProgressBars: true
enableTelemetry: true
lockfileFilename: "yarn.lock"
